/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

import funcionario.CadastroEventos;
import funcionario.RespostaDaDoacao;
import voluntario.CadastroVoluntarioCNPJ;
import voluntario.CadastroVoluntarioCPF;
import voluntario.Doacao;


public class MenuVoluntario extends javax.swing.JFrame {

    /**
     * Creates new form MenuVoluntario
     */
    public static ArrayList <CadastroEventos> listaCadastroEventos = new ArrayList<>();
     CadastroVoluntarioCPF cvCPF = new CadastroVoluntarioCPF ();
     CadastroVoluntarioCNPJ cvCNPJ = new CadastroVoluntarioCNPJ();
    public static ArrayList <Doacao> listaDoacao = new ArrayList<>();
    public static List <RespostaDaDoacao> listaRespostaDoacao = new ArrayList<>();
    public static CadastroEventos ce = new CadastroEventos();
    public MenuVoluntario() {
        initComponents();
        limparCampos ();
        setMascara();
        taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", "")); 
        exibir ();
        
    }
    public MenuVoluntario (ArrayList <CadastroEventos> listaCadastroEventos ){
        initComponents();
        limparCampos ();
        setMascara();
        this.listaCadastroEventos = listaCadastroEventos;
        taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", "")); 
        exibir();
        
    }
    public MenuVoluntario(CadastroVoluntarioCPF cvCPF) {  
        initComponents();
        limparCampos ();
        setMascara();
        this.cvCPF = cvCPF;
        exibir();
        
    }   
    public MenuVoluntario (CadastroVoluntarioCNPJ cvCNPJ){
        initComponents();
        limparCampos ();
        setMascara();
        this.cvCNPJ = cvCNPJ;
        exibir();
    }
    public MenuVoluntario (List <RespostaDaDoacao>listaRespostaDoacao ){
        initComponents();
        this.listaRespostaDoacao = listaRespostaDoacao;
        exibir();
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpAbas = new javax.swing.JTabbedPane();
        pEventosNaONG = new javax.swing.JPanel();
        lTituloEventosNaONG = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListaEventos = new javax.swing.JTextArea();
        lDaraParaSeAssociarAoTrabalhoDisponivel = new javax.swing.JLabel();
        bAsssociarAEvento = new javax.swing.JButton();
        bMenuPrincipal = new javax.swing.JButton();
        tfRecebeCodigoEvento = new javax.swing.JTextField();
        pDoacao = new javax.swing.JPanel();
        lTituloDoacao = new javax.swing.JLabel();
        lDataDaEntrega = new javax.swing.JLabel();
        lFormaDeEntregaDeDoacao = new javax.swing.JLabel();
        cbRecebeFormaDeEntrega = new javax.swing.JComboBox<>();
        lDoacaoUnica = new javax.swing.JLabel();
        cbRecebeRespostaDeDoacaoUnica = new javax.swing.JComboBox<>();
        lValor = new javax.swing.JLabel();
        tfRecebeValor = new javax.swing.JTextField();
        bEnviaDoacaoParaAnalise = new javax.swing.JButton();
        ftfRecebeDataDeEntrega = new javax.swing.JFormattedTextField();
        pPerfil = new javax.swing.JPanel();
        lPerfil = new javax.swing.JLabel();
        lRespostaReferenteADoacao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taListaRespostaReferenteADoacao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTituloEventosNaONG.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lTituloEventosNaONG.setText("Eventos Na ONG");

        taListaEventos.setColumns(20);
        taListaEventos.setRows(5);
        jScrollPane1.setViewportView(taListaEventos);

        lDaraParaSeAssociarAoTrabalhoDisponivel.setText("Digite o Código Para se Associar ao Trabalho Disponivel no Evento: ");

        bAsssociarAEvento.setText("Associar a Evento");
        bAsssociarAEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsssociarAEventoActionPerformed(evt);
            }
        });

        bMenuPrincipal.setText("Voltar Para Menu");
        bMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuPrincipalActionPerformed(evt);
            }
        });

        tfRecebeCodigoEvento.setText("jTextField1");

        javax.swing.GroupLayout pEventosNaONGLayout = new javax.swing.GroupLayout(pEventosNaONG);
        pEventosNaONG.setLayout(pEventosNaONGLayout);
        pEventosNaONGLayout.setHorizontalGroup(
            pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventosNaONGLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(lTituloEventosNaONG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEventosNaONGLayout.createSequentialGroup()
                .addGroup(pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEventosNaONGLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pEventosNaONGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pEventosNaONGLayout.createSequentialGroup()
                                .addComponent(lDaraParaSeAssociarAoTrabalhoDisponivel)
                                .addGap(18, 18, 18)
                                .addComponent(tfRecebeCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 52, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEventosNaONGLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bAsssociarAEvento)))))
                .addContainerGap())
        );
        pEventosNaONGLayout.setVerticalGroup(
            pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventosNaONGLayout.createSequentialGroup()
                .addComponent(lTituloEventosNaONG)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDaraParaSeAssociarAoTrabalhoDisponivel)
                    .addComponent(tfRecebeCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(bAsssociarAEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(bMenuPrincipal)
                .addContainerGap())
        );

        tpAbas.addTab("Eventos Na ONG", pEventosNaONG);

        lTituloDoacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lTituloDoacao.setText("Doação");

        lDataDaEntrega.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lDataDaEntrega.setText("Data Da Entrega:");

        lFormaDeEntregaDeDoacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lFormaDeEntregaDeDoacao.setText("Forma De Entrega de Doação:");

        cbRecebeFormaDeEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrega Presencial", "Entrega Na ONG" }));
        cbRecebeFormaDeEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRecebeFormaDeEntregaActionPerformed(evt);
            }
        });

        lDoacaoUnica.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lDoacaoUnica.setText("Doação Única:");

        cbRecebeRespostaDeDoacaoUnica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        lValor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lValor.setText("Valor:");

        tfRecebeValor.setText("jTextField2");

        bEnviaDoacaoParaAnalise.setText("Enviar Doação Para Análise");
        bEnviaDoacaoParaAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviaDoacaoParaAnaliseActionPerformed(evt);
            }
        });

        ftfRecebeDataDeEntrega.setText("jFormattedTextField1");

        javax.swing.GroupLayout pDoacaoLayout = new javax.swing.GroupLayout(pDoacao);
        pDoacao.setLayout(pDoacaoLayout);
        pDoacaoLayout.setHorizontalGroup(
            pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDoacaoLayout.createSequentialGroup()
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDoacaoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bEnviaDoacaoParaAnalise)
                            .addGroup(pDoacaoLayout.createSequentialGroup()
                                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lFormaDeEntregaDeDoacao)
                                    .addComponent(lDataDaEntrega)
                                    .addComponent(lDoacaoUnica)
                                    .addComponent(lValor))
                                .addGap(18, 18, 18)
                                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbRecebeFormaDeEntrega, 0, 237, Short.MAX_VALUE)
                                    .addComponent(cbRecebeRespostaDeDoacaoUnica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfRecebeValor)
                                    .addComponent(ftfRecebeDataDeEntrega)))))
                    .addGroup(pDoacaoLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lTituloDoacao)))
                .addGap(39, 88, Short.MAX_VALUE))
        );
        pDoacaoLayout.setVerticalGroup(
            pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDoacaoLayout.createSequentialGroup()
                .addComponent(lTituloDoacao)
                .addGap(18, 18, 18)
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lDataDaEntrega)
                    .addComponent(ftfRecebeDataDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDoacaoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lFormaDeEntregaDeDoacao))
                    .addGroup(pDoacaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbRecebeFormaDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDoacaoUnica)
                    .addComponent(cbRecebeRespostaDeDoacaoUnica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lValor)
                    .addComponent(tfRecebeValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(bEnviaDoacaoParaAnalise)
                .addGap(60, 60, 60))
        );

        tpAbas.addTab("Doação", pDoacao);

        lPerfil.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lPerfil.setText("Pefil");

        lRespostaReferenteADoacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lRespostaReferenteADoacao.setText("Resposta Referente a Doação:");

        taListaRespostaReferenteADoacao.setColumns(20);
        taListaRespostaReferenteADoacao.setRows(5);
        jScrollPane2.setViewportView(taListaRespostaReferenteADoacao);

        javax.swing.GroupLayout pPerfilLayout = new javax.swing.GroupLayout(pPerfil);
        pPerfil.setLayout(pPerfilLayout);
        pPerfilLayout.setHorizontalGroup(
            pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPerfilLayout.createSequentialGroup()
                .addGroup(pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPerfilLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lPerfil))
                    .addGroup(pPerfilLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lRespostaReferenteADoacao)
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pPerfilLayout.setVerticalGroup(
            pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPerfilLayout.createSequentialGroup()
                .addComponent(lPerfil)
                .addGap(18, 18, 18)
                .addGroup(pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRespostaReferenteADoacao)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 240, Short.MAX_VALUE))
        );

        tpAbas.addTab("Perfil", pPerfil);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAbas)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tpAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEnviaDoacaoParaAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviaDoacaoParaAnaliseActionPerformed

        String data = ftfRecebeDataDeEntrega.getText();
        String formaDeEntrega = cbRecebeFormaDeEntrega.getSelectedItem().toString();
        String doacaoUnica = cbRecebeRespostaDeDoacaoUnica.getSelectedItem().toString();
        String doacaoValorString = tfRecebeValor.getText();
        double doacaoValor = Double.parseDouble(doacaoValorString);

        
        
        if (this.cvCPF!=null){
            Doacao doacao = new Doacao(listaDoacao.size(),data, formaDeEntrega, doacaoUnica, doacaoValor, cvCPF);
            listaDoacao.add(doacao);
            MenuFuncionario menu = new MenuFuncionario(listaDoacao);
                
            }
        else if (this.cvCNPJ!=null){
            Doacao doacao = new Doacao(listaDoacao.size(),data, formaDeEntrega, doacaoUnica, doacaoValor, cvCNPJ);
            listaDoacao.add(doacao);
            MenuFuncionario menu = new MenuFuncionario(listaDoacao);
                
            }
         else {
            JOptionPane.showMessageDialog(null,"Não foi possivel completa sua doação");
            }
        
        limparCampos();
    }//GEN-LAST:event_bEnviaDoacaoParaAnaliseActionPerformed

    private void cbRecebeFormaDeEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRecebeFormaDeEntregaActionPerformed

    }//GEN-LAST:event_cbRecebeFormaDeEntregaActionPerformed

    private void bMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuPrincipalActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bMenuPrincipalActionPerformed

    private void bAsssociarAEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAsssociarAEventoActionPerformed
        int codigoEvento = Integer.parseInt(tfRecebeCodigoEvento.getText());
        for (int i=0; i< listaCadastroEventos.size();i++){
            CadastroEventos indiceNaLista = listaCadastroEventos.get(i);
            if (indiceNaLista.getCodigoEvento() == codigoEvento && cvCPF != null){
                JOptionPane.showMessageDialog(null,indiceNaLista.cadastroEVerificacaoDeQuantidadeDeVagas(cvCPF.getNome()));
            }
            else {
                JOptionPane.showMessageDialog(null,indiceNaLista.cadastroEVerificacaoDeQuantidadeDeVagas(cvCNPJ.getNome()));
            }
        }
        taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", ""));
    }//GEN-LAST:event_bAsssociarAEventoActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVoluntario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAsssociarAEvento;
    private javax.swing.JButton bEnviaDoacaoParaAnalise;
    private javax.swing.JButton bMenuPrincipal;
    private javax.swing.JComboBox<String> cbRecebeFormaDeEntrega;
    private javax.swing.JComboBox<String> cbRecebeRespostaDeDoacaoUnica;
    private javax.swing.JFormattedTextField ftfRecebeDataDeEntrega;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lDaraParaSeAssociarAoTrabalhoDisponivel;
    private javax.swing.JLabel lDataDaEntrega;
    private javax.swing.JLabel lDoacaoUnica;
    private javax.swing.JLabel lFormaDeEntregaDeDoacao;
    private javax.swing.JLabel lPerfil;
    private javax.swing.JLabel lRespostaReferenteADoacao;
    private javax.swing.JLabel lTituloDoacao;
    private javax.swing.JLabel lTituloEventosNaONG;
    private javax.swing.JLabel lValor;
    private javax.swing.JPanel pDoacao;
    private javax.swing.JPanel pEventosNaONG;
    private javax.swing.JPanel pPerfil;
    private javax.swing.JTextArea taListaEventos;
    private javax.swing.JTextArea taListaRespostaReferenteADoacao;
    private javax.swing.JTextField tfRecebeCodigoEvento;
    private javax.swing.JTextField tfRecebeValor;
    private javax.swing.JTabbedPane tpAbas;
    // End of variables declaration//GEN-END:variables
    
    public void limparCampos (){
        ftfRecebeDataDeEntrega.setText(null);
        tfRecebeValor.setText(null);
        tfRecebeCodigoEvento.setText(null);
        tfRecebeValor.setText(null);
    }
    
     public void setMascara(){
    try{
        MaskFormatter mask = new MaskFormatter("##/##/####");
        mask.install(ftfRecebeDataDeEntrega);
        }catch(java.text.ParseException ex){}
   
}
     public void exibir (){
        taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", "")); 
        taListaRespostaReferenteADoacao.setText(listaRespostaDoacao.toString());
     }
   
}
