/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import funcionario.CadastroEventos;
import gerais.CadastroGeral;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import static view.Login.listaVoluntarios;
import static view.Login.tipoDeMenu;



/**
 *
 * @author Victor
 */
public class MenuVoluntario extends javax.swing.JFrame {

    /**
     * Creates new form MenuVoluntario
     */
    public static ArrayList <CadastroEventos> listaCadastroEventos = new ArrayList<>();
    public static ArrayList <CadastroGeral> listaVoluntarios = new ArrayList<>();
    public static CadastroGeral cg = new CadastroGeral();
    public MenuVoluntario(CadastroGeral cg) {
        initComponents();
        limparCampos ();
        this.cg= cg;
        taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", ""));
        
    }
    
    public MenuVoluntario (ArrayList <CadastroEventos> listaCadastroEventos ){
        initComponents();
        limparCampos ();
        this.listaCadastroEventos = listaCadastroEventos;
        taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", ""));
        
    }
    
    public MenuVoluntario() {
        
        
    }   
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpAbas = new javax.swing.JTabbedPane();
        pEventosNaONG = new javax.swing.JPanel();
        lTituloEventosNaONG = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListaEventos = new javax.swing.JTextArea();
        lDaraParaSeAssociarAoTrabalhoDisponivel = new javax.swing.JLabel();
        bAsssociarAEvento = new javax.swing.JButton();
        bMenuPrincipal = new javax.swing.JButton();
        ftfRecebeData = new javax.swing.JFormattedTextField();
        pDoacao = new javax.swing.JPanel();
        lTituloDoacao = new javax.swing.JLabel();
        lDataDaEntrega = new javax.swing.JLabel();
        tfRecebeDataDaEntrega = new javax.swing.JTextField();
        lFormaDeEntregaDeDoacao = new javax.swing.JLabel();
        cbRecebeFormaDeEntrega = new javax.swing.JComboBox<>();
        lDoacaoUnica = new javax.swing.JLabel();
        cbRecebeRespostaDeDoacaoUnica = new javax.swing.JComboBox<>();
        lValor = new javax.swing.JLabel();
        tfRecebeValor = new javax.swing.JTextField();
        bEnviaDoacaoParaAnalise = new javax.swing.JButton();
        pPerfil = new javax.swing.JPanel();
        lPerfil = new javax.swing.JLabel();
        lRespostaReferenteADoacao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taListaRespostaReferenteADoacao = new javax.swing.JTextArea();
        lEventosQueEstaAssociado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taListaEventosQueVocêEstaAssociado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTituloEventosNaONG.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lTituloEventosNaONG.setText("Eventos Na ONG");

        taListaEventos.setColumns(20);
        taListaEventos.setRows(5);
        jScrollPane1.setViewportView(taListaEventos);

        lDaraParaSeAssociarAoTrabalhoDisponivel.setText("Digite a Data Para se Associar ao Trabalho Disponivel no Evento: ");

        bAsssociarAEvento.setText("Associar a Evento");
        bAsssociarAEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsssociarAEventoActionPerformed(evt);
            }
        });

        bMenuPrincipal.setText("Voltar Para Menu");
        bMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuPrincipalActionPerformed(evt);
            }
        });

        ftfRecebeData.setText("jFormattedTextField1");
        ftfRecebeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfRecebeDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pEventosNaONGLayout = new javax.swing.GroupLayout(pEventosNaONG);
        pEventosNaONG.setLayout(pEventosNaONGLayout);
        pEventosNaONGLayout.setHorizontalGroup(
            pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventosNaONGLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(lTituloEventosNaONG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEventosNaONGLayout.createSequentialGroup()
                .addGroup(pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEventosNaONGLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pEventosNaONGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pEventosNaONGLayout.createSequentialGroup()
                                .addComponent(lDaraParaSeAssociarAoTrabalhoDisponivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfRecebeData, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 62, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEventosNaONGLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bAsssociarAEvento)))))
                .addContainerGap())
        );
        pEventosNaONGLayout.setVerticalGroup(
            pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventosNaONGLayout.createSequentialGroup()
                .addComponent(lTituloEventosNaONG)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pEventosNaONGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDaraParaSeAssociarAoTrabalhoDisponivel)
                    .addComponent(ftfRecebeData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(bAsssociarAEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(bMenuPrincipal)
                .addContainerGap())
        );

        tpAbas.addTab("Eventos Na ONG", pEventosNaONG);

        lTituloDoacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lTituloDoacao.setText("Doação");

        lDataDaEntrega.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lDataDaEntrega.setText("Data Da Entrega:");

        tfRecebeDataDaEntrega.setText("jTextField1");

        lFormaDeEntregaDeDoacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lFormaDeEntregaDeDoacao.setText("Forma De Entrega de Doação:");

        cbRecebeFormaDeEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrega Presencial", " ", "PIX" }));
        cbRecebeFormaDeEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRecebeFormaDeEntregaActionPerformed(evt);
            }
        });

        lDoacaoUnica.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lDoacaoUnica.setText("Doação Única:");

        cbRecebeRespostaDeDoacaoUnica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        lValor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lValor.setText("Valor:");

        tfRecebeValor.setText("jTextField2");

        bEnviaDoacaoParaAnalise.setText("Enviar Doação Para Análise");
        bEnviaDoacaoParaAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviaDoacaoParaAnaliseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDoacaoLayout = new javax.swing.GroupLayout(pDoacao);
        pDoacao.setLayout(pDoacaoLayout);
        pDoacaoLayout.setHorizontalGroup(
            pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDoacaoLayout.createSequentialGroup()
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDoacaoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bEnviaDoacaoParaAnalise)
                            .addGroup(pDoacaoLayout.createSequentialGroup()
                                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lFormaDeEntregaDeDoacao)
                                    .addComponent(lDataDaEntrega)
                                    .addComponent(lDoacaoUnica)
                                    .addComponent(lValor))
                                .addGap(18, 18, 18)
                                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfRecebeDataDaEntrega)
                                    .addComponent(cbRecebeFormaDeEntrega, 0, 237, Short.MAX_VALUE)
                                    .addComponent(cbRecebeRespostaDeDoacaoUnica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfRecebeValor)))))
                    .addGroup(pDoacaoLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lTituloDoacao)))
                .addGap(39, 88, Short.MAX_VALUE))
        );
        pDoacaoLayout.setVerticalGroup(
            pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDoacaoLayout.createSequentialGroup()
                .addComponent(lTituloDoacao)
                .addGap(18, 18, 18)
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDataDaEntrega)
                    .addComponent(tfRecebeDataDaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDoacaoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lFormaDeEntregaDeDoacao))
                    .addGroup(pDoacaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbRecebeFormaDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDoacaoUnica)
                    .addComponent(cbRecebeRespostaDeDoacaoUnica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lValor)
                    .addComponent(tfRecebeValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(bEnviaDoacaoParaAnalise)
                .addGap(60, 60, 60))
        );

        tpAbas.addTab("Doação", pDoacao);

        lPerfil.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lPerfil.setText("Pefil");

        lRespostaReferenteADoacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lRespostaReferenteADoacao.setText("Resposta Referente a Doação:");

        taListaRespostaReferenteADoacao.setColumns(20);
        taListaRespostaReferenteADoacao.setRows(5);
        jScrollPane2.setViewportView(taListaRespostaReferenteADoacao);

        lEventosQueEstaAssociado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lEventosQueEstaAssociado.setText("Eventos que você esta Associado:");

        taListaEventosQueVocêEstaAssociado.setColumns(20);
        taListaEventosQueVocêEstaAssociado.setRows(5);
        jScrollPane3.setViewportView(taListaEventosQueVocêEstaAssociado);

        javax.swing.GroupLayout pPerfilLayout = new javax.swing.GroupLayout(pPerfil);
        pPerfil.setLayout(pPerfilLayout);
        pPerfilLayout.setHorizontalGroup(
            pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPerfilLayout.createSequentialGroup()
                .addGroup(pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPerfilLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lPerfil))
                    .addGroup(pPerfilLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pPerfilLayout.createSequentialGroup()
                                .addComponent(lEventosQueEstaAssociado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPerfilLayout.createSequentialGroup()
                                .addComponent(lRespostaReferenteADoacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pPerfilLayout.setVerticalGroup(
            pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPerfilLayout.createSequentialGroup()
                .addComponent(lPerfil)
                .addGap(18, 18, 18)
                .addGroup(pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRespostaReferenteADoacao)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEventosQueEstaAssociado)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 106, Short.MAX_VALUE))
        );

        tpAbas.addTab("Perfil", pPerfil);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tpAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void bAsssociarAEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAsssociarAEventoActionPerformed

        for (int i=0; i< listaCadastroEventos.size();i++){
               CadastroEventos indiceNaLista = listaCadastroEventos.get(i);
               if (indiceNaLista.getDadaDoEvento().equals(ftfRecebeData.getText())){
                  JOptionPane.showMessageDialog(null,indiceNaLista.cadastroEVerificacaoDeQuantidadeDeVagas(cg));
               }
           }
        taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", ""));
    }//GEN-LAST:event_bAsssociarAEventoActionPerformed

    private void cbRecebeFormaDeEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRecebeFormaDeEntregaActionPerformed
        
    }//GEN-LAST:event_cbRecebeFormaDeEntregaActionPerformed

    private void bEnviaDoacaoParaAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviaDoacaoParaAnaliseActionPerformed
        
    }//GEN-LAST:event_bEnviaDoacaoParaAnaliseActionPerformed

    private void bMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuPrincipalActionPerformed
       Menu menu = new Menu();
       menu.setVisible(true);
       dispose();
    }//GEN-LAST:event_bMenuPrincipalActionPerformed

    private void ftfRecebeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfRecebeDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfRecebeDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVoluntario(cg).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAsssociarAEvento;
    private javax.swing.JButton bEnviaDoacaoParaAnalise;
    private javax.swing.JButton bMenuPrincipal;
    private javax.swing.JComboBox<String> cbRecebeFormaDeEntrega;
    private javax.swing.JComboBox<String> cbRecebeRespostaDeDoacaoUnica;
    private javax.swing.JFormattedTextField ftfRecebeData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lDaraParaSeAssociarAoTrabalhoDisponivel;
    private javax.swing.JLabel lDataDaEntrega;
    private javax.swing.JLabel lDoacaoUnica;
    private javax.swing.JLabel lEventosQueEstaAssociado;
    private javax.swing.JLabel lFormaDeEntregaDeDoacao;
    private javax.swing.JLabel lPerfil;
    private javax.swing.JLabel lRespostaReferenteADoacao;
    private javax.swing.JLabel lTituloDoacao;
    private javax.swing.JLabel lTituloEventosNaONG;
    private javax.swing.JLabel lValor;
    private javax.swing.JPanel pDoacao;
    private javax.swing.JPanel pEventosNaONG;
    private javax.swing.JPanel pPerfil;
    private javax.swing.JTextArea taListaEventos;
    private javax.swing.JTextArea taListaEventosQueVocêEstaAssociado;
    private javax.swing.JTextArea taListaRespostaReferenteADoacao;
    private javax.swing.JTextField tfRecebeDataDaEntrega;
    private javax.swing.JTextField tfRecebeValor;
    private javax.swing.JTabbedPane tpAbas;
    // End of variables declaration//GEN-END:variables
    
    public void limparCampos (){
        tfRecebeDataDaEntrega.setText(null);
        tfRecebeValor.setText(null);
        ftfRecebeData.setText(null);
    }
    
    public void setMascara(){
    try{
        MaskFormatter mask = new MaskFormatter("##/##/####");
        mask.install(ftfRecebeData);
        }catch(java.text.ParseException ex){}
   
    }
   
}
