/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Victor
 */
public class MenuFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form MenuFuncionario
     */
    public MenuFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        tbCadastrarVoluntario = new javax.swing.JToggleButton();
        tbDoacao = new javax.swing.JToggleButton();
        tbCadastroDeEventos = new javax.swing.JToggleButton();
        tbCadastroDeTrabalhos = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lTitulo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lTitulo.setText("Menu Funcionário");

        tbCadastrarVoluntario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbCadastrarVoluntario.setText("Cadastrar Voluntário");
        tbCadastrarVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCadastrarVoluntarioActionPerformed(evt);
            }
        });

        tbDoacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbDoacao.setText("Aceitar Doações");
        tbDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDoacaoActionPerformed(evt);
            }
        });

        tbCadastroDeEventos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbCadastroDeEventos.setText("Cadastrar Eventos");
        tbCadastroDeEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCadastroDeEventosActionPerformed(evt);
            }
        });

        tbCadastroDeTrabalhos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbCadastroDeTrabalhos.setText("Cadastrar Trabalhos");
        tbCadastroDeTrabalhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCadastroDeTrabalhosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lTitulo)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbCadastrarVoluntario)
                            .addComponent(tbCadastroDeEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbCadastroDeTrabalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(tbCadastrarVoluntario)
                .addGap(18, 18, 18)
                .addComponent(tbDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbCadastroDeEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbCadastroDeTrabalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbCadastrarVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCadastrarVoluntarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCadastrarVoluntarioActionPerformed

    private void tbDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDoacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDoacaoActionPerformed

    private void tbCadastroDeEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCadastroDeEventosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCadastroDeEventosActionPerformed

    private void tbCadastroDeTrabalhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCadastroDeTrabalhosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCadastroDeTrabalhosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JToggleButton tbCadastrarVoluntario;
    private javax.swing.JToggleButton tbCadastroDeEventos;
    private javax.swing.JToggleButton tbCadastroDeTrabalhos;
    private javax.swing.JToggleButton tbDoacao;
    // End of variables declaration//GEN-END:variables
}
