/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import funcionario.CadastroEventos;
import funcionario.CadastroTrabalho;
import funcionario.Funcionario;
import gerais.CadastroGeral;
import java.awt.ComponentOrientation;
import java.awt.Label;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;
import javax.swing.text.MaskFormatter;
import voluntario.CadastroVoluntarioCNPJ;
import voluntario.CadastroVoluntarioCPF;

/**
 *
 * @author Victor
 */
public class MenuFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form MenuVoluntario
     */
    
    public static ArrayList <CadastroGeral> listaVoluntarios = new ArrayList <> ();
    public static ArrayList <Funcionario> listaFuncionarios = new ArrayList <> ();
    public static ArrayList <CadastroEventos> listaCadastroEventos = new ArrayList<>();
    SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
    public MenuFuncionario() {
        initComponents();
        limparCampos();
        setMascara();
        cbComboEscolhePeriodoDeTempoDisponivel.getSelectedObjects(); 
        taListarVoluntarios.setText(listaVoluntarios.toString().replace("[", "").replace("]", ""));
        taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", ""));
    }

    public MenuFuncionario(ArrayList <Funcionario> listaFuncionarios ){
        initComponents();
        this.listaFuncionarios  = listaFuncionarios;
        taListarVoluntarios.setText(listaVoluntarios.toString().replace("[", "").replace("]", ""));
        taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", ""));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpAbas = new javax.swing.JTabbedPane();
        pCadastrarNovoVoluntario = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        lCPFCNPJ = new javax.swing.JLabel();
        tfRecebeNome = new javax.swing.JTextField();
        tfRecebeCPFCNPJ = new javax.swing.JTextField();
        bSalvarVoluntario = new javax.swing.JButton();
        bRemoverVoluntario = new javax.swing.JButton();
        spListarFuncionarios = new javax.swing.JScrollPane();
        taListarVoluntarios = new javax.swing.JTextArea();
        lInformeONumeroParaRemoveroVoluntario = new javax.swing.JLabel();
        tfRecebeNumeroParaRemoverVoluntario = new javax.swing.JTextField();
        lIdade = new javax.swing.JLabel();
        tfRecebeIdade = new javax.swing.JTextField();
        lEndereco = new javax.swing.JLabel();
        tfRecebeEndereco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbComboEscolhePeriodoDeTempoDisponivel = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        pAceitarDoacao = new javax.swing.JPanel();
        lDoacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListarDoacoes = new javax.swing.JTextArea();
        bRemoverDoacao = new javax.swing.JToggleButton();
        lDoacaoNaoRemovidasSeramConsideradasComoAceitas = new javax.swing.JLabel();
        lInformeONumeroDaDoacaoQueDesejaRemover = new javax.swing.JLabel();
        tfRecebendoDoacaoParaRemover = new javax.swing.JTextField();
        pCadastroDeEventos = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lValorGastoParaExecutarEvento = new javax.swing.JLabel();
        tfRecebeValorGastoParExecutarEvento = new javax.swing.JTextField();
        lObjetivoDoEvento = new javax.swing.JLabel();
        tfRecebeObjetivoDoEvento = new javax.swing.JTextField();
        lDataDoEvento = new javax.swing.JLabel();
        lDuracaoDoEvento = new javax.swing.JLabel();
        tfRecebeDuracaoDoEvento = new javax.swing.JTextField();
        lMetaDeArrecadacaoDoEvento = new javax.swing.JLabel();
        tfRecebeMetaDeArrecadacaoDoEvento = new javax.swing.JTextField();
        lFuncionarioResposavel = new javax.swing.JLabel();
        tfRecebeFuncionarioResposavel = new javax.swing.JTextField();
        bSalvarEvento = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taListaEventos = new javax.swing.JTextArea();
        bRemoveEvento = new javax.swing.JButton();
        tfRecebeDataDeEventoParaRemover = new javax.swing.JTextField();
        lInformeADataParaRemoverEvento = new javax.swing.JLabel();
        ftfRecebeData = new javax.swing.JFormattedTextField();
        lInformeOTrabalhoNecessarioParaOsVoluntarios = new javax.swing.JLabel();
        tfRecebeTrabalhoParaVoluntarios = new javax.swing.JTextField();
        lVagas = new javax.swing.JLabel();
        tfRecebeVagas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpAbas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        lNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lNome.setText("Nome:");

        lCPFCNPJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lCPFCNPJ.setText("CPF/CNPJ:");

        tfRecebeNome.setText("jTextField1");

        tfRecebeCPFCNPJ.setText("jTextField2");

        bSalvarVoluntario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bSalvarVoluntario.setText("Salvar");
        bSalvarVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarVoluntarioActionPerformed(evt);
            }
        });

        bRemoverVoluntario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bRemoverVoluntario.setText("Remover");
        bRemoverVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverVoluntarioActionPerformed(evt);
            }
        });

        taListarVoluntarios.setColumns(20);
        taListarVoluntarios.setRows(5);
        spListarFuncionarios.setViewportView(taListarVoluntarios);

        lInformeONumeroParaRemoveroVoluntario.setText("Informe o Numero Para Remover o Voluntário");

        tfRecebeNumeroParaRemoverVoluntario.setText("jTextField3");
        tfRecebeNumeroParaRemoverVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRecebeNumeroParaRemoverVoluntarioActionPerformed(evt);
            }
        });

        lIdade.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lIdade.setText("Idade:");

        tfRecebeIdade.setText("jTextField1");

        lEndereco.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lEndereco.setText("Endereço:");

        tfRecebeEndereco.setText("jTextField2");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Tempo Disponível: ");

        cbComboEscolhePeriodoDeTempoDisponivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));
        cbComboEscolhePeriodoDeTempoDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbComboEscolhePeriodoDeTempoDisponivelActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCadastrarNovoVoluntarioLayout = new javax.swing.GroupLayout(pCadastrarNovoVoluntario);
        pCadastrarNovoVoluntario.setLayout(pCadastrarNovoVoluntarioLayout);
        pCadastrarNovoVoluntarioLayout.setHorizontalGroup(
            pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                        .addComponent(spListarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(bSalvarVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                        .addComponent(lInformeONumeroParaRemoveroVoluntario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfRecebeNumeroParaRemoverVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bRemoverVoluntario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(77, 77, 77))
            .addGroup(pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfRecebeIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                            .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lNome)
                                .addComponent(lIdade)
                                .addComponent(lEndereco)
                                .addComponent(lCPFCNPJ))
                            .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(tfRecebeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfRecebeEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfRecebeCPFCNPJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(cbComboEscolhePeriodoDeTempoDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastrarNovoVoluntarioLayout.setVerticalGroup(
            pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(tfRecebeNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIdade)
                    .addComponent(tfRecebeIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEndereco)
                    .addComponent(tfRecebeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbComboEscolhePeriodoDeTempoDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCPFCNPJ)
                    .addComponent(tfRecebeCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spListarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(bSalvarVoluntario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pCadastrarNovoVoluntarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(pCadastrarNovoVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lInformeONumeroParaRemoveroVoluntario)
                            .addComponent(tfRecebeNumeroParaRemoverVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRemoverVoluntario))
                        .addGap(110, 110, 110)))
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        tpAbas.addTab("Cadastrar ou remover Voluntário", pCadastrarNovoVoluntario);

        lDoacoes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lDoacoes.setText("Doações");

        taListarDoacoes.setColumns(20);
        taListarDoacoes.setRows(5);
        jScrollPane1.setViewportView(taListarDoacoes);

        bRemoverDoacao.setText("Remover Doações");
        bRemoverDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverDoacaoActionPerformed(evt);
            }
        });

        lDoacaoNaoRemovidasSeramConsideradasComoAceitas.setText("As doações que não forem removidas serão consideradas como aceitas  ");

        lInformeONumeroDaDoacaoQueDesejaRemover.setText("Informe o Numero Da Doação que Deseja Remover");

        tfRecebendoDoacaoParaRemover.setText("jTextField5");

        javax.swing.GroupLayout pAceitarDoacaoLayout = new javax.swing.GroupLayout(pAceitarDoacao);
        pAceitarDoacao.setLayout(pAceitarDoacaoLayout);
        pAceitarDoacaoLayout.setHorizontalGroup(
            pAceitarDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAceitarDoacaoLayout.createSequentialGroup()
                .addGroup(pAceitarDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAceitarDoacaoLayout.createSequentialGroup()
                        .addGap(0, 221, Short.MAX_VALUE)
                        .addComponent(lDoacaoNaoRemovidasSeramConsideradasComoAceitas))
                    .addGroup(pAceitarDoacaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(pAceitarDoacaoLayout.createSequentialGroup()
                        .addGroup(pAceitarDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAceitarDoacaoLayout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(lDoacoes))
                            .addGroup(pAceitarDoacaoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lInformeONumeroDaDoacaoQueDesejaRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRecebendoDoacaoParaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAceitarDoacaoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bRemoverDoacao))
        );
        pAceitarDoacaoLayout.setVerticalGroup(
            pAceitarDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAceitarDoacaoLayout.createSequentialGroup()
                .addComponent(lDoacoes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lDoacaoNaoRemovidasSeramConsideradasComoAceitas)
                .addGap(63, 63, 63)
                .addGroup(pAceitarDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lInformeONumeroDaDoacaoQueDesejaRemover)
                    .addComponent(tfRecebendoDoacaoParaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(bRemoverDoacao)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        tpAbas.addTab("Aceitar ou remover Doacão", pAceitarDoacao);

        lTitulo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lTitulo.setText("Cadastrar Eventos");

        lValorGastoParaExecutarEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lValorGastoParaExecutarEvento.setText("Valor Gasto Para Executar Evento");

        tfRecebeValorGastoParExecutarEvento.setText("jTextField1");

        lObjetivoDoEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lObjetivoDoEvento.setText("Objetivo Do Evento");

        tfRecebeObjetivoDoEvento.setText("jTextField2");

        lDataDoEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lDataDoEvento.setText("Data Do Evento");

        lDuracaoDoEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lDuracaoDoEvento.setText("Duração Do Evento");

        tfRecebeDuracaoDoEvento.setText("jTextField4");

        lMetaDeArrecadacaoDoEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lMetaDeArrecadacaoDoEvento.setText("Meta De Arrecadação Do Evento");

        tfRecebeMetaDeArrecadacaoDoEvento.setText("jTextField5");

        lFuncionarioResposavel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lFuncionarioResposavel.setText("Funcionário Resposável");

        tfRecebeFuncionarioResposavel.setText("jTextField6");

        bSalvarEvento.setText("Salvar Evento");
        bSalvarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarEventoActionPerformed(evt);
            }
        });

        taListaEventos.setColumns(20);
        taListaEventos.setRows(5);
        jScrollPane2.setViewportView(taListaEventos);

        bRemoveEvento.setText("Remover Evento");
        bRemoveEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveEventoActionPerformed(evt);
            }
        });

        tfRecebeDataDeEventoParaRemover.setText("jTextField2");

        lInformeADataParaRemoverEvento.setText("Informe a Data do Evento Para Remover");

        ftfRecebeData.setText("jFormattedTextField1");

        lInformeOTrabalhoNecessarioParaOsVoluntarios.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lInformeOTrabalhoNecessarioParaOsVoluntarios.setText("Informe o Trabalho necessário para os Voluntários");

        tfRecebeTrabalhoParaVoluntarios.setText("jTextField1");

        lVagas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lVagas.setText("Vagas:");

        tfRecebeVagas.setText("jTextField2");

        javax.swing.GroupLayout pCadastroDeEventosLayout = new javax.swing.GroupLayout(pCadastroDeEventos);
        pCadastroDeEventos.setLayout(pCadastroDeEventosLayout);
        pCadastroDeEventosLayout.setHorizontalGroup(
            pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lTitulo))
                    .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                                .addComponent(lInformeADataParaRemoverEvento)
                                .addGap(18, 18, 18)
                                .addComponent(tfRecebeDataDeEventoParaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSalvarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRemoveEvento))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lValorGastoParaExecutarEvento)
                                .addComponent(lDataDoEvento)
                                .addComponent(lDuracaoDoEvento)
                                .addComponent(lMetaDeArrecadacaoDoEvento)
                                .addComponent(lFuncionarioResposavel)
                                .addComponent(lInformeOTrabalhoNecessarioParaOsVoluntarios))
                            .addGap(70, 70, 70))
                        .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lObjetivoDoEvento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lVagas)
                        .addGap(300, 300, 300)))
                .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfRecebeValorGastoParExecutarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRecebeDuracaoDoEvento)
                            .addComponent(tfRecebeMetaDeArrecadacaoDoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfRecebeObjetivoDoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(ftfRecebeData, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(tfRecebeFuncionarioResposavel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(tfRecebeTrabalhoParaVoluntarios)
                    .addComponent(tfRecebeVagas))
                .addGap(123, 123, 123))
        );
        pCadastroDeEventosLayout.setVerticalGroup(
            pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                .addComponent(lTitulo)
                .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lValorGastoParaExecutarEvento)
                            .addComponent(tfRecebeValorGastoParExecutarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lObjetivoDoEvento)
                            .addComponent(tfRecebeObjetivoDoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDataDoEvento)
                            .addComponent(ftfRecebeData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDuracaoDoEvento)
                            .addComponent(tfRecebeDuracaoDoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lMetaDeArrecadacaoDoEvento)
                            .addComponent(tfRecebeMetaDeArrecadacaoDoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lFuncionarioResposavel)
                            .addComponent(tfRecebeFuncionarioResposavel))
                        .addGap(18, 18, 18)
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lInformeOTrabalhoNecessarioParaOsVoluntarios)
                            .addComponent(tfRecebeTrabalhoParaVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lVagas)
                            .addComponent(tfRecebeVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCadastroDeEventosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSalvarEvento)))
                .addGap(35, 35, 35)
                .addGroup(pCadastroDeEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRecebeDataDeEventoParaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lInformeADataParaRemoverEvento)
                    .addComponent(bRemoveEvento))
                .addContainerGap())
        );

        tpAbas.addTab("Cadastrar Eventos", pCadastroDeEventos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tpAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAbas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalvarVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarVoluntarioActionPerformed
        CadastroVoluntarioCPF voluntariocpf;
        CadastroVoluntarioCNPJ voluntariocnpj;
        String nome = tfRecebeNome.getText() ;
        String idade = tfRecebeIdade.getText();
        String endereço = tfRecebeEndereco.getText();
        String cpfCNPJ = tfRecebeCPFCNPJ.getText();
        int idadeInteiro = Integer.parseInt(idade);
        String tempoDisponivel =  cbComboEscolhePeriodoDeTempoDisponivel.getSelectedItem().toString();
        int tamanhoDoDocumento = cpfCNPJ.length();
        int i=listaVoluntarios.size();
        if (tamanhoDoDocumento == 11){
            voluntariocpf = new CadastroVoluntarioCPF(cpfCNPJ,tempoDisponivel, nome, idadeInteiro, endereço);
            listaVoluntarios.add(voluntariocpf);
            Login login = new Login(listaVoluntarios);
        }
        else if (tamanhoDoDocumento == 14) {
            voluntariocnpj = new CadastroVoluntarioCNPJ(cpfCNPJ,tempoDisponivel, nome, idadeInteiro, endereço);
            listaVoluntarios.add(voluntariocnpj);
            Login login = new Login(listaVoluntarios);
         }
        limparCampos();
        taListarVoluntarios.setText(listaVoluntarios.toString().replace("[", "").replace("]", ""));
    }//GEN-LAST:event_bSalvarVoluntarioActionPerformed

    private void bRemoverVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverVoluntarioActionPerformed
        String recebeNome = tfRecebeNumeroParaRemoverVoluntario.getText();
        for (int i=0; i< listaVoluntarios.size();i++){
               CadastroGeral indiceNaLista = listaVoluntarios.get(i);
               if (indiceNaLista.getNome().equals(recebeNome)){
                   listaVoluntarios.remove(indiceNaLista);
               }
           }
        limparCampos(); //verificar se precisa repetir
        taListarVoluntarios.setText(listaVoluntarios.toString().replace("[", "").replace("]", ""));
        
        
    }//GEN-LAST:event_bRemoverVoluntarioActionPerformed

    private void bSalvarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarEventoActionPerformed
        CadastroEventos ce;
        CadastroTrabalho cadastroTrabalho;
        String valorGastoParaExecutarEvento = tfRecebeValorGastoParExecutarEvento.getText();
        double valorGastoParaExecutarEventoDouble = Double.parseDouble(valorGastoParaExecutarEvento);
        String objetivoDoEvento = tfRecebeObjetivoDoEvento.getText();
	String data  = ftfRecebeData.getText();
	String duracaoEvento = tfRecebeDuracaoDoEvento.getText();
        String metaArrecadacaoEvento = tfRecebeMetaDeArrecadacaoDoEvento.getText();
	double metaArrecadacaoEventoDouble = Double.parseDouble(metaArrecadacaoEvento);
	String nomeFuncionarioResposavel = tfRecebeFuncionarioResposavel.getText();
        String tipoTrabalho = tfRecebeTrabalhoParaVoluntarios.getText();
        String vagas = tfRecebeVagas.getText();
        int vagasInt = Integer.parseInt(vagas);
                
        for (int i=0; i < listaFuncionarios.size(); i++){
            Funcionario funcionarioResposavelPeloEvento = listaFuncionarios.get(i); 
            if (funcionarioResposavelPeloEvento.getNome().equals(nomeFuncionarioResposavel)){
                funcionarioResposavelPeloEvento = listaFuncionarios.get(i);
                
                cadastroTrabalho = new CadastroTrabalho(tipoTrabalho,vagasInt);
                ce = new CadastroEventos(valorGastoParaExecutarEventoDouble, objetivoDoEvento, data, duracaoEvento, metaArrecadacaoEventoDouble, funcionarioResposavelPeloEvento, cadastroTrabalho);
                listaCadastroEventos.add(ce);
                taListaEventos.setText(listaCadastroEventos.toString().replace("[", "").replace("]", ""));
                MenuVoluntario menu = new MenuVoluntario(listaCadastroEventos);
                limparCampos();
                
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Funcionario Não Encontrado");
                limparCampos();
            }
                
        }    
    }//GEN-LAST:event_bSalvarEventoActionPerformed

    private void bRemoveEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveEventoActionPerformed
       String recebeData = tfRecebeDataDeEventoParaRemover.getText();
        for (int i=0; i< listaCadastroEventos.size();i++){
               CadastroEventos indiceNaLista = listaCadastroEventos.get(i);
               if (indiceNaLista.getDadaDoEvento().equals(recebeData)){
                   listaCadastroEventos.remove(indiceNaLista);
               }
           }
        limparCampos();
        taListarVoluntarios.setText(listaVoluntarios.toString().replace("[", "").replace("]", ""));
        
    }//GEN-LAST:event_bRemoveEventoActionPerformed

    private void bRemoverDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverDoacaoActionPerformed
       
    }//GEN-LAST:event_bRemoverDoacaoActionPerformed

    private void tfRecebeNumeroParaRemoverVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRecebeNumeroParaRemoverVoluntarioActionPerformed
        
    }//GEN-LAST:event_tfRecebeNumeroParaRemoverVoluntarioActionPerformed

    private void cbComboEscolhePeriodoDeTempoDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbComboEscolhePeriodoDeTempoDisponivelActionPerformed
        
    }//GEN-LAST:event_cbComboEscolhePeriodoDeTempoDisponivelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Menu menu = new Menu();
       menu.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRemoveEvento;
    private javax.swing.JToggleButton bRemoverDoacao;
    private javax.swing.JButton bRemoverVoluntario;
    private javax.swing.JButton bSalvarEvento;
    private javax.swing.JButton bSalvarVoluntario;
    private javax.swing.JComboBox<String> cbComboEscolhePeriodoDeTempoDisponivel;
    private javax.swing.JFormattedTextField ftfRecebeData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lCPFCNPJ;
    private javax.swing.JLabel lDataDoEvento;
    private javax.swing.JLabel lDoacaoNaoRemovidasSeramConsideradasComoAceitas;
    private javax.swing.JLabel lDoacoes;
    private javax.swing.JLabel lDuracaoDoEvento;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lFuncionarioResposavel;
    private javax.swing.JLabel lIdade;
    private javax.swing.JLabel lInformeADataParaRemoverEvento;
    private javax.swing.JLabel lInformeONumeroDaDoacaoQueDesejaRemover;
    private javax.swing.JLabel lInformeONumeroParaRemoveroVoluntario;
    private javax.swing.JLabel lInformeOTrabalhoNecessarioParaOsVoluntarios;
    private javax.swing.JLabel lMetaDeArrecadacaoDoEvento;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lObjetivoDoEvento;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lVagas;
    private javax.swing.JLabel lValorGastoParaExecutarEvento;
    private javax.swing.JPanel pAceitarDoacao;
    private javax.swing.JPanel pCadastrarNovoVoluntario;
    private javax.swing.JPanel pCadastroDeEventos;
    private javax.swing.JScrollPane spListarFuncionarios;
    private javax.swing.JTextArea taListaEventos;
    private javax.swing.JTextArea taListarDoacoes;
    private javax.swing.JTextArea taListarVoluntarios;
    private javax.swing.JTextField tfRecebeCPFCNPJ;
    private javax.swing.JTextField tfRecebeDataDeEventoParaRemover;
    private javax.swing.JTextField tfRecebeDuracaoDoEvento;
    private javax.swing.JTextField tfRecebeEndereco;
    private javax.swing.JTextField tfRecebeFuncionarioResposavel;
    private javax.swing.JTextField tfRecebeIdade;
    private javax.swing.JTextField tfRecebeMetaDeArrecadacaoDoEvento;
    private javax.swing.JTextField tfRecebeNome;
    private javax.swing.JTextField tfRecebeNumeroParaRemoverVoluntario;
    private javax.swing.JTextField tfRecebeObjetivoDoEvento;
    private javax.swing.JTextField tfRecebeTrabalhoParaVoluntarios;
    private javax.swing.JTextField tfRecebeVagas;
    private javax.swing.JTextField tfRecebeValorGastoParExecutarEvento;
    private javax.swing.JTextField tfRecebendoDoacaoParaRemover;
    private javax.swing.JTabbedPane tpAbas;
    // End of variables declaration//GEN-END:variables

    public void limparCampos (){
        tfRecebeNome.setText(null);
        tfRecebeIdade.setText(null);
        tfRecebeEndereco.setText(null);
        tfRecebeCPFCNPJ.setText(null);
        tfRecebeNumeroParaRemoverVoluntario.setText(null);
        tfRecebeValorGastoParExecutarEvento.setText(null);
        tfRecebeObjetivoDoEvento.setText(null);
        ftfRecebeData.setText(null);
        tfRecebeDuracaoDoEvento.setText(null);
        tfRecebeFuncionarioResposavel.setText(null);
        tfRecebeDataDeEventoParaRemover.setText(null);
        tfRecebeMetaDeArrecadacaoDoEvento.setText(null);
        tfRecebeTrabalhoParaVoluntarios.setText(null);
        tfRecebeVagas.setText(null);
    }
    
   public void setMascara(){
    try{
        MaskFormatter mask = new MaskFormatter("##/##/####");
        mask.install(ftfRecebeData);
        }catch(java.text.ParseException ex){}
   
}
   
   public void removerElementoDaLista (ArrayList <Object> lista , String elementoParaRemover ){
       for (int i=0; i< listaVoluntarios.size();i++){
               CadastroGeral indiceNaLista = listaVoluntarios.get(i);
               if (indiceNaLista.getNome().equals(elementoParaRemover)){
                   listaVoluntarios.remove(indiceNaLista);
               }
           }
   }
 
}
